/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQueryUser.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   user/v1
// Description:
//   This should be for movie quotes but it says User
// Classes:
//   GTLQueryUser (3 custom class methods, 8 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLUserUser;

@interface GTLQueryUser : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (nonatomic, assign) long long age;
@property (nonatomic, copy) NSString *entityKey;
@property (nonatomic, assign) long long gender;
@property (nonatomic, assign) long long limit;
@property (nonatomic, copy) NSString *order;
@property (nonatomic, copy) NSString *pageToken;
@property (nonatomic, copy) NSString *userBucket;
@property (nonatomic, copy) NSString *email;

#pragma mark - "user" methods
// These create a GTLQueryUser object.

// Method: user.user.create
// create users as well as update the data
//  Authorization scope(s):
//   kGTLAuthScopeUserUserinfoEmail
// Fetches a GTLUserUser.
+ (instancetype)queryForUserCreateWithObject:(GTLUserUser *)object;

// Method: user.user.delete
//  Authorization scope(s):
//   kGTLAuthScopeUserUserinfoEmail
// Fetches a GTLUserUser.
+ (instancetype)queryForUserDeleteWithEntityKey:(NSString *)entityKey;

// Method: user.user.list
// returns a list of all of the users
//  Optional:
//   age: long long
//   gender: long long
//   limit: long long
//   order: NSString
//   pageToken: NSString
//   userBucket: NSString
//  Authorization scope(s):
//   kGTLAuthScopeUserUserinfoEmail
// Fetches a GTLUserCollection.
+ (instancetype)queryForUserList;

@end
