/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLUser.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   user/v1
// Description:
//   This should be for movie quotes but it says User

#import "GTLUserConstants.h"

#import "GTLUserCollection.h"
#import "GTLUserUser.h"

#import "GTLQueryUser.h"
#import "GTLServiceUser.h"
