/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLUser_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   user/v1
// Description:
//   This should be for movie quotes but it says User

#import "GTLUserConstants.m"

#import "GTLUserCollection.m"
#import "GTLUserGeoPtMessage.m"
#import "GTLUserUser.m"

#import "GTLQueryUser.m"
#import "GTLServiceUser.m"
