/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLUserCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   user/v1
// Description:
//   This should be for movie quotes but it says User
// Classes:
//   GTLUserCollection (0 custom class methods, 2 custom properties)

#import "GTLUserCollection.h"

#import "GTLUserUser.h"

// ----------------------------------------------------------------------------
//
//   GTLUserCollection
//

@implementation GTLUserCollection
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"items" : [GTLUserUser class]
  };
  return map;
}

@end
