/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLUserUser.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   user/v1
// Description:
//   This should be for movie quotes but it says User
// Classes:
//   GTLUserUser (0 custom class methods, 26 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLUserUser
//

@interface GTLUserUser : GTLObject
@property (nonatomic, retain) NSNumber *age;  // longLongValue
@property (nonatomic, retain) NSNumber *ageHigh;  // longLongValue
@property (nonatomic, retain) NSNumber *ageLow;  // longLongValue
@property (nonatomic, retain) NSArray *ageRange;  // of NSNumber (longLongValue)
@property (nonatomic, copy) NSString *bio;
@property (nonatomic, copy) NSString *confirmationCode;
@property (nonatomic, retain) NSNumber *dating;  // longLongValue
@property (nonatomic, retain) NSNumber *distanceAway;  // longLongValue
@property (nonatomic, retain) NSNumber *distanceOfSearch;  // longLongValue
@property (nonatomic, copy) NSString *email;
@property (nonatomic, copy) NSString *entityKey;
@property (nonatomic, copy) NSString *firstName;
@property (nonatomic, retain) NSNumber *gender;  // longLongValue
@property (nonatomic, retain) NSNumber *lat;  // doubleValue
@property (nonatomic, copy) NSString *likedYou;
@property (nonatomic, retain) NSArray *likedArray;  // of NSString
@property (nonatomic, retain) NSNumber *lon;  // doubleValue
@property (nonatomic, retain) NSNumber *lookingFor;  // longLongValue
@property (nonatomic, retain) NSArray *matchedArray;  // of NSString
@property (nonatomic, copy) NSString *password;
@property (nonatomic, retain) NSNumber *phoneNumber;  // longLongValue
@property (nonatomic, retain) NSArray *profileGif;  // of NSString
@property (nonatomic, retain) NSArray *profileVideoUrls;  // of NSString
@property (nonatomic, retain) NSArray *skippedArray;  // of NSString
@property (nonatomic, copy) NSString *userBucket;
@property (nonatomic, copy) NSString *userLocation;
@end
