/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLUserGeoPtMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   user/v1
// Description:
//   This should be for movie quotes but it says User
// Classes:
//   GTLUserGeoPtMessage (0 custom class methods, 2 custom properties)

#import "GTLUserGeoPtMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLUserGeoPtMessage
//

@implementation GTLUserGeoPtMessage
@dynamic lat, lon;
@end
